version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env